image:
  file: .gitpod.Dockerfile

tasks:
  # Mitigation for https://github.com/gitpod-io/gitpod/issues/6460 
  - name: Postinstall .NET 6.0 and dev certificates
    init: |
      mkdir -p $DOTNET_ROOT && curl -fsSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel $DOTNET_VERSION --install-dir $DOTNET_ROOT 
      dotnet dev-certs https 
      dotnet restore

vscode:
  extensions:
    - Ionide.Ionide-fsharp@5.5.9
    - muhammad-sammy.csharp